### ISSUE TITLE
Feature request: enable/disable trackEvent in runtime dynamically

### ISSUE THREAD

**Issue by zackshen** [aptabase/tauri-plugin-aptabase#8]
The `tauri-plugin-aptabase` plugin seems convenient to use currently. I hope to have the ability to dynamically enable or disable the `trackEvent` feature. For example, having a setting option on the interface to turn off log tracking without the need to restart the app.

**Comment by goenning** [comment]
Hey Zack, that’s a great suggestion and something I’d like to have on all SDKs too. 

For now, the best option would be to wrap the trackEvent in your app and add this skip logic there, probably storing this config in users device too.

**Comment by zackshen** [comment]
yes, thanks @goenning , i would wrap the trackEvent .
